# (PART) Model {-}
# 模型基础

```{r}
library(modelr)
options(na.action = na.warn)

library(ggplot2)
library(dplyr);
```

```{r}
ggplot(sim1, aes(x, y)) + 
  geom_point()
```

```{r}
# 一种更方便的创建 tbl dataframe 的方式
models <- tibble(
  a1 = runif(250, -20, 40),
  a2 = runif(250, -5, 5)
)

ggplot(sim1, aes(x, y)) + 
  geom_abline(aes(intercept = a1, slope = a2), data = models, alpha = 1/4) + 
  geom_point()
```

一个函数和一个自变量，然后输出
```{r}
model1 <- function(a, data) {
  a[1] + data$x * a[2]
}
model1(c(7,1.5), sim1)
```

根均方误差
```{r}
measure_distance <- function(mod, data) {
  diff <- data$y - model1(mod, data)
  sqrt(mean(diff^2))
}

measure_distance(c(7, 1.5), sim1)
```

mutate 添加新变量

```{r}
sim1_dist <- function(a1, a2) {
  measure_distance(c(a1, a2), sim1)
}

models <- models %>%
 mutate(dist = purrr::map2_dbl(a1, a2, sim1_dist))

models
```

map2_dbl 没有 data选项，会报错。
```{r}
#models %>%
#purrr::map2_dbl(a1, a2, sim1_dist())
```

`-dist` 表示最小的最亮
```{r}
ggplot(sim1, aes(x, y)) + 
  geom_point(size = 2, colour = "grey30") + 
  geom_abline(
    aes(intercept = a1, slope = a2, colour = -dist), 
    data = filter(models, rank(dist) <= 10)
  ) # 这个-dist不是很理解，暂时理解为从小往大排，由浅入深
```


用散点图把拟合的最好的 10 个点突出出来

```{r}
ggplot(models, aes(a1, a2)) + 
  geom_point(data = filter(models, rank(dist) < 10), size = 4, colour = 'red') + 
  geom_point(aes(colour = -dist))
```

等间距图

```{r}
grid <- expand.grid(
  a1 = seq(-5, 20, length = 25),
  a2 = seq(1, 3, length = 25)
) %>%
  mutate(dist = purrr::map2_dbl(a1, a2, sim1_dist))

grid %>%
  ggplot(aes(a1, a2)) + 
  geom_point(data = filter(grid, rank(dist) < 10), size = 4, colour = 'red') + 
  geom_point(aes(colour = -dist))
```

再看看拟合情况
```{r}
ggplot(sim1, aes(x, y)) + 
  geom_point(size = 2, colour = 'grey30') +
  geom_abline(
    aes(intercept = a1, slope = a2, colour = -dist),
    data = filter(grid, rank(dist) <= 10)
  )
```

牛顿法
```{r}
best <- optim(c(0, 0), measure_distance, data = sim1)
best$par # 返回的是 list 还有其他的一些参数

ggplot(sim1, aes(x, y )) +
  geom_point(size = 2, colour = 'grey30') + 
  geom_abline(intercept =best$par[1], slope = best$par[2])
```

另外的一种线性代数的拟合方式
```{r}
sim1_mod <- lm(y ~ x, data = sim1)
coef(sim1_mod)
```

